# Generated by Django 4.2.7 on 2023-11-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_estatus_certificados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campoPrueba', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='certificados',
            old_name='idCertificados',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='estatus',
            old_name='idEstatus',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='idRol',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuario',
            new_name='id',
        ),
    ]
