# Generated by Django 4.2.7 on 2023-11-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_asesoradosporasesor_datoscorporales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planalimenticio_con_estatus', to='aplicacion.estatus')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planfisico_con_estatus', to='aplicacion.estatus')),
            ],
        ),
        migrations.CreateModel(
            name='TienePlanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReporte', models.IntegerField()),
                ('idPlanAlimenticio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.planalimenticio')),
                ('idPlanFisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.planfisico')),
                ('idUsuarioAsesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
